/**
 * 
 */
package controladores;

/**
 * @author ra00170556
 *
 */
public enum TipoDesenho {
	RETA, CIRCULO, PONTO, CURVA_DO_DRAGAO, RETA_ELASTICA, CIRCULO_ELASTICO, RETANGULO_ELASTICO, POLIGONO_ELASTICO, 
	RETA_POLIGONAL, APAGAR_DESENHO
}
